# Script to compare discrete features of cell lines and their effect on response

# import necessary libraries and functions using MTS_functions.R
source("./MTS_functions.R")


#---- Parameters ----

# directory with data: should be the folder generated by MTS_Data_Processing.R
base_dir <- # INSERT PATH TO DATA HERE


#---- Load cell line information ----
X <- data.table::fread() # INSERT path to cell line feature data here

#---- Load assay results ----

# dose response curve parameters
DRC <- data.table::fread(paste0(base_dir, "/DRC_TABLE_cb.csv")) %>%
  dplyr::distinct(ccle_name, pert_mfc_id, auc, log2.ic50) %>%
  tidyr::gather(key = "dose", value = "response", auc, log2.ic50) %>%
  dplyr::filter(is.finite(response))

# separate tables for DRC metrics
IC50 <- dplyr::filter(DRC, dose == "log2.ic50")
AUC <- dplyr::filter(DRC, dose == "auc")

# LFC table
LFC <- data.table::fread(paste0(base_dir, "/LFC_TABLE.csv")) %>%
  dplyr::distinct(pert_name, ccle_name, pert_idose, pert_mfc_id, LFC.cb) %>%
  dplyr::rename(response = LFC.cb) %>%
  dplyr::rename(dose = pert_idose) %>%
  dplyr::filter(is.finite(response))

# compounds
compounds <- LFC %>%
  dplyr::select(pert_mfc_id, pert_name) %>%
  dplyr::distinct()


#---- Run analysis ----

for (i in 1:nrow(compounds)) {
  comp <- compounds[i, "pert_mfc_id"]
  df <- AUC %>%  # change to metric of choice
    dplyr::filter(pert_mfc_id == comp)
  y <- df$response; names(y) <- df$ccle_name
  t_table <- discrete_test(X, y)
  readr::write_csv(t_table, paste0(base_dir, "/t_table_", comp, ".csv"))
}
